<?php

use Illuminate\Database\Seeder;

class PaymentServiceApiParametersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('payment_service_api_parameters')->delete();
        
        \DB::table('payment_service_api_parameters')->insert(array (
            0 => 
            array (
                'id' => 1,
                'external_system_id' => 361,
                'payment_services_api_id' => 15,
                'name_ar' => 'serviceparamin361',
                'name_en' => 'phone',
                'position' => 1,
                'visible' => 'yes',
                'required' => 'yes',
                'type' => 'N',
                'is_client_id' => 'yes',
                'default_value' => '010',
                'min_length' => 11,
                'max_length' => 11,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:55',
                'updated_at' => '2018-01-01 10:03:55',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'external_system_id' => 3,
                'payment_services_api_id' => 16,
                'name_ar' => 'رقم العميل',
                'name_en' => 'Phone',
                'position' => 1,
                'visible' => 'yes',
                'required' => 'yes',
                'type' => 'N',
                'is_client_id' => 'yes',
                'default_value' => '012',
                'min_length' => 10,
                'max_length' => 11,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:55',
                'updated_at' => '2018-01-01 10:03:55',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'external_system_id' => 2,
                'payment_services_api_id' => 17,
                'name_ar' => 'رقم العميل',
                'name_en' => 'Phone',
                'position' => 1,
                'visible' => 'yes',
                'required' => 'yes',
                'type' => 'N',
                'is_client_id' => 'yes',
                'default_value' => '011',
                'min_length' => 10,
                'max_length' => 11,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:55',
                'updated_at' => '2018-01-01 10:03:55',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'external_system_id' => 1729,
                'payment_services_api_id' => 17,
                'name_ar' => 'serviceparamin1729',
                'name_en' => 'Topup Type',
                'position' => 2,
                'visible' => '',
                'required' => 'yes',
                'type' => 'N',
                'is_client_id' => '',
                'default_value' => '900',
                'min_length' => 3,
                'max_length' => 3,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:55',
                'updated_at' => '2018-01-01 10:03:55',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'external_system_id' => 282,
                'payment_services_api_id' => 24,
                'name_ar' => 'serviceparamin282',
                'name_en' => 'Account',
                'position' => 1,
                'visible' => 'yes',
                'required' => 'yes',
                'type' => 'N',
                'is_client_id' => 'yes',
                'default_value' => '01',
                'min_length' => 16,
                'max_length' => 16,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:55',
                'updated_at' => '2018-01-01 10:03:55',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'external_system_id' => 283,
                'payment_services_api_id' => 25,
                'name_ar' => 'serviceparamin283',
                'name_en' => 'Account',
                'position' => 1,
                'visible' => 'yes',
                'required' => 'yes',
                'type' => 'N',
                'is_client_id' => 'yes',
                'default_value' => '01',
                'min_length' => 16,
                'max_length' => 16,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:55',
                'updated_at' => '2018-01-01 10:03:55',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'external_system_id' => 1329,
                'payment_services_api_id' => 30,
                'name_ar' => 'serviceparamin1329',
                'name_en' => 'Customer Number',
                'position' => 1,
                'visible' => 'yes',
                'required' => 'yes',
                'type' => 'N',
                'is_client_id' => 'yes',
                'default_value' => '',
                'min_length' => 11,
                'max_length' => 11,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:56',
                'updated_at' => '2018-01-01 10:03:56',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'external_system_id' => 608,
                'payment_services_api_id' => 31,
                'name_ar' => 'رقم حساب الطالب',
                'name_en' => 'Account Number',
                'position' => 1,
                'visible' => 'yes',
                'required' => 'yes',
                'type' => 'C',
                'is_client_id' => 'yes',
                'default_value' => '',
                'min_length' => 14,
                'max_length' => 20,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:56',
                'updated_at' => '2018-01-01 10:03:56',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'external_system_id' => 609,
                'payment_services_api_id' => 31,
                'name_ar' => 'serviceparamin609',
                'name_en' => 'Bill Number',
                'position' => 2,
                'visible' => '',
                'required' => '',
                'type' => 'C',
                'is_client_id' => '',
                'default_value' => '',
                'min_length' => 1,
                'max_length' => 20,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:56',
                'updated_at' => '2018-01-01 10:03:56',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'external_system_id' => 610,
                'payment_services_api_id' => 31,
                'name_ar' => 'serviceparamin610',
                'name_en' => 'ePay Bill Record ID',
                'position' => 3,
                'visible' => '',
                'required' => '',
                'type' => 'C',
                'is_client_id' => '',
                'default_value' => '',
                'min_length' => 1,
                'max_length' => 50,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:56',
                'updated_at' => '2018-01-01 10:03:56',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'external_system_id' => 611,
                'payment_services_api_id' => 31,
                'name_ar' => 'serviceparamin611',
                'name_en' => 'Fee Amount',
                'position' => 4,
                'visible' => '',
                'required' => '',
                'type' => 'C',
                'is_client_id' => '',
                'default_value' => '0',
                'min_length' => 1,
                'max_length' => 10,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:56',
                'updated_at' => '2018-01-01 10:03:56',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'external_system_id' => 612,
                'payment_services_api_id' => 31,
                'name_ar' => 'serviceparamin612',
                'name_en' => 'Biller ID',
                'position' => 5,
                'visible' => '',
                'required' => '',
                'type' => 'L',
                'is_client_id' => '',
                'default_value' => '22661',
                'min_length' => 1,
                'max_length' => 5,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:56',
                'updated_at' => '2018-01-01 10:03:56',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'external_system_id' => 613,
                'payment_services_api_id' => 31,
                'name_ar' => 'serviceparamin613',
                'name_en' => 'Service Type',
                'position' => 6,
                'visible' => '',
                'required' => '',
                'type' => 'C',
                'is_client_id' => '',
                'default_value' => 'CAU',
                'min_length' => 1,
                'max_length' => 3,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:56',
                'updated_at' => '2018-01-01 10:03:56',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'external_system_id' => 581,
                'payment_services_api_id' => 32,
                'name_ar' => 'رقم حساب الطالب',
                'name_en' => 'Account Number',
                'position' => 1,
                'visible' => 'yes',
                'required' => 'yes',
                'type' => 'C',
                'is_client_id' => 'yes',
                'default_value' => '',
                'min_length' => 14,
                'max_length' => 20,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:56',
                'updated_at' => '2018-01-01 10:03:56',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'external_system_id' => 582,
                'payment_services_api_id' => 32,
                'name_ar' => 'serviceparamin582',
                'name_en' => 'Bill Number',
                'position' => 2,
                'visible' => '',
                'required' => '',
                'type' => 'C',
                'is_client_id' => '',
                'default_value' => '',
                'min_length' => 1,
                'max_length' => 20,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:56',
                'updated_at' => '2018-01-01 10:03:56',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'external_system_id' => 583,
                'payment_services_api_id' => 32,
                'name_ar' => 'serviceparamin583',
                'name_en' => 'ePay Bill Record ID',
                'position' => 3,
                'visible' => '',
                'required' => '',
                'type' => 'C',
                'is_client_id' => '',
                'default_value' => '',
                'min_length' => 1,
                'max_length' => 50,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:56',
                'updated_at' => '2018-01-01 10:03:56',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'external_system_id' => 584,
                'payment_services_api_id' => 32,
                'name_ar' => 'serviceparamin584',
                'name_en' => 'Fee Amount',
                'position' => 4,
                'visible' => '',
                'required' => '',
                'type' => 'C',
                'is_client_id' => '',
                'default_value' => '0',
                'min_length' => 1,
                'max_length' => 10,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:56',
                'updated_at' => '2018-01-01 10:03:56',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'external_system_id' => 585,
                'payment_services_api_id' => 32,
                'name_ar' => 'serviceparamin585',
                'name_en' => 'Biller ID',
                'position' => 5,
                'visible' => '',
                'required' => '',
                'type' => 'L',
                'is_client_id' => '',
                'default_value' => '22662',
                'min_length' => 1,
                'max_length' => 5,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:56',
                'updated_at' => '2018-01-01 10:03:56',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'external_system_id' => 586,
                'payment_services_api_id' => 32,
                'name_ar' => 'serviceparamin586',
                'name_en' => 'Service Type',
                'position' => 6,
                'visible' => '',
                'required' => '',
                'type' => 'C',
                'is_client_id' => '',
                'default_value' => 'CAU',
                'min_length' => 1,
                'max_length' => 3,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:56',
                'updated_at' => '2018-01-01 10:03:56',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'external_system_id' => 602,
                'payment_services_api_id' => 33,
                'name_ar' => 'رقم حساب الطالب',
                'name_en' => 'Account Number',
                'position' => 1,
                'visible' => 'yes',
                'required' => 'yes',
                'type' => 'C',
                'is_client_id' => 'yes',
                'default_value' => '',
                'min_length' => 14,
                'max_length' => 20,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:56',
                'updated_at' => '2018-01-01 10:03:56',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'external_system_id' => 603,
                'payment_services_api_id' => 33,
                'name_ar' => 'serviceparamin603',
                'name_en' => 'Bill Number',
                'position' => 2,
                'visible' => '',
                'required' => '',
                'type' => 'C',
                'is_client_id' => '',
                'default_value' => '',
                'min_length' => 1,
                'max_length' => 20,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:56',
                'updated_at' => '2018-01-01 10:03:56',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'external_system_id' => 604,
                'payment_services_api_id' => 33,
                'name_ar' => 'serviceparamin604',
                'name_en' => 'ePay Bill Record ID',
                'position' => 3,
                'visible' => '',
                'required' => '',
                'type' => 'C',
                'is_client_id' => '',
                'default_value' => '',
                'min_length' => 1,
                'max_length' => 50,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:56',
                'updated_at' => '2018-01-01 10:03:56',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'external_system_id' => 605,
                'payment_services_api_id' => 33,
                'name_ar' => 'serviceparamin605',
                'name_en' => 'Fee Amount',
                'position' => 4,
                'visible' => '',
                'required' => '',
                'type' => 'C',
                'is_client_id' => '',
                'default_value' => '0',
                'min_length' => 1,
                'max_length' => 10,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:56',
                'updated_at' => '2018-01-01 10:03:56',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'external_system_id' => 606,
                'payment_services_api_id' => 33,
                'name_ar' => 'serviceparamin606',
                'name_en' => 'Biller ID',
                'position' => 5,
                'visible' => '',
                'required' => '',
                'type' => 'L',
                'is_client_id' => '',
                'default_value' => '22661',
                'min_length' => 1,
                'max_length' => 5,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:56',
                'updated_at' => '2018-01-01 10:03:56',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'external_system_id' => 607,
                'payment_services_api_id' => 33,
                'name_ar' => 'serviceparamin607',
                'name_en' => 'Service Type',
                'position' => 6,
                'visible' => '',
                'required' => '',
                'type' => 'C',
                'is_client_id' => '',
                'default_value' => 'CAU',
                'min_length' => 1,
                'max_length' => 3,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:56',
                'updated_at' => '2018-01-01 10:03:56',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'external_system_id' => 596,
                'payment_services_api_id' => 34,
                'name_ar' => 'رقم حساب الطالب',
                'name_en' => 'Account Number',
                'position' => 1,
                'visible' => 'yes',
                'required' => 'yes',
                'type' => 'C',
                'is_client_id' => 'yes',
                'default_value' => '',
                'min_length' => 14,
                'max_length' => 20,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:56',
                'updated_at' => '2018-01-01 10:03:56',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'external_system_id' => 597,
                'payment_services_api_id' => 34,
                'name_ar' => 'serviceparamin597',
                'name_en' => 'Bill Number',
                'position' => 2,
                'visible' => '',
                'required' => '',
                'type' => 'C',
                'is_client_id' => '',
                'default_value' => '',
                'min_length' => 1,
                'max_length' => 20,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:57',
                'updated_at' => '2018-01-01 10:03:57',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'external_system_id' => 598,
                'payment_services_api_id' => 34,
                'name_ar' => 'serviceparamin598',
                'name_en' => 'ePay Bill Record ID',
                'position' => 3,
                'visible' => '',
                'required' => '',
                'type' => 'C',
                'is_client_id' => '',
                'default_value' => '',
                'min_length' => 1,
                'max_length' => 50,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:57',
                'updated_at' => '2018-01-01 10:03:57',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'external_system_id' => 599,
                'payment_services_api_id' => 34,
                'name_ar' => 'serviceparamin599',
                'name_en' => 'Fee Amount',
                'position' => 4,
                'visible' => '',
                'required' => '',
                'type' => 'C',
                'is_client_id' => '',
                'default_value' => '0',
                'min_length' => 1,
                'max_length' => 10,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:57',
                'updated_at' => '2018-01-01 10:03:57',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'external_system_id' => 600,
                'payment_services_api_id' => 34,
                'name_ar' => 'serviceparamin600',
                'name_en' => 'Biller ID',
                'position' => 5,
                'visible' => '',
                'required' => '',
                'type' => 'L',
                'is_client_id' => '',
                'default_value' => '22661',
                'min_length' => 1,
                'max_length' => 5,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:57',
                'updated_at' => '2018-01-01 10:03:57',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'external_system_id' => 601,
                'payment_services_api_id' => 34,
                'name_ar' => 'serviceparamin601',
                'name_en' => 'Service Type',
                'position' => 6,
                'visible' => '',
                'required' => '',
                'type' => 'C',
                'is_client_id' => '',
                'default_value' => 'CAU',
                'min_length' => 1,
                'max_length' => 3,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:57',
                'updated_at' => '2018-01-01 10:03:57',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'external_system_id' => 1349,
                'payment_services_api_id' => 51,
                'name_ar' => 'serviceparamin1349',
                'name_en' => 'Customer Number',
                'position' => 1,
                'visible' => 'yes',
                'required' => 'yes',
                'type' => 'N',
                'is_client_id' => 'yes',
                'default_value' => '',
                'min_length' => 10,
                'max_length' => 12,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:58',
                'updated_at' => '2018-01-01 10:03:58',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'external_system_id' => 1292,
                'payment_services_api_id' => 53,
                'name_ar' => 'serviceparamin1292',
                'name_en' => 'Customer Number',
                'position' => 1,
                'visible' => 'yes',
                'required' => 'yes',
                'type' => 'N',
                'is_client_id' => 'yes',
                'default_value' => '',
                'min_length' => 10,
                'max_length' => 11,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:58',
                'updated_at' => '2018-01-01 10:03:58',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'external_system_id' => 1293,
                'payment_services_api_id' => 53,
                'name_ar' => 'serviceparamin1293',
                'name_en' => 'Package Amount',
                'position' => 2,
                'visible' => '',
                'required' => 'yes',
                'type' => 'N',
                'is_client_id' => '',
                'default_value' => '25',
                'min_length' => 1,
                'max_length' => 10,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:58',
                'updated_at' => '2018-01-01 10:03:58',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'external_system_id' => 507,
                'payment_services_api_id' => 55,
                'name_ar' => 'رقم حساب العميل',
                'name_en' => 'Account Number',
                'position' => 1,
                'visible' => 'yes',
                'required' => 'yes',
                'type' => 'N',
                'is_client_id' => 'yes',
                'default_value' => '',
                'min_length' => 1,
                'max_length' => 20,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:58',
                'updated_at' => '2018-01-01 10:03:58',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'external_system_id' => 508,
                'payment_services_api_id' => 55,
                'name_ar' => 'serviceparamin508',
                'name_en' => 'Bill Number',
                'position' => 2,
                'visible' => '',
                'required' => '',
                'type' => 'C',
                'is_client_id' => '',
                'default_value' => '',
                'min_length' => 1,
                'max_length' => 20,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:58',
                'updated_at' => '2018-01-01 10:03:58',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'external_system_id' => 509,
                'payment_services_api_id' => 55,
                'name_ar' => 'serviceparamin509',
                'name_en' => 'ePay Bill Record ID',
                'position' => 3,
                'visible' => '',
                'required' => '',
                'type' => 'C',
                'is_client_id' => '',
                'default_value' => '',
                'min_length' => 1,
                'max_length' => 50,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:58',
                'updated_at' => '2018-01-01 10:03:58',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'external_system_id' => 522,
                'payment_services_api_id' => 55,
                'name_ar' => 'serviceparamin522',
                'name_en' => 'Fee Amount',
                'position' => 4,
                'visible' => '',
                'required' => '',
                'type' => 'C',
                'is_client_id' => '',
                'default_value' => '0',
                'min_length' => 1,
                'max_length' => 10,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:58',
                'updated_at' => '2018-01-01 10:03:58',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'external_system_id' => 561,
                'payment_services_api_id' => 55,
                'name_ar' => 'serviceparamin561',
                'name_en' => 'Biller ID',
                'position' => 5,
                'visible' => 'yes',
                'required' => 'yes',
                'type' => 'C',
                'is_client_id' => '',
                'default_value' => '99007',
                'min_length' => 1,
                'max_length' => 5,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:58',
                'updated_at' => '2018-01-01 10:03:58',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'external_system_id' => 562,
                'payment_services_api_id' => 55,
                'name_ar' => 'serviceparamin562',
                'name_en' => 'Service Type',
                'position' => 6,
                'visible' => '',
                'required' => '',
                'type' => 'C',
                'is_client_id' => '',
                'default_value' => 'ECP',
                'min_length' => 1,
                'max_length' => 3,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:58',
                'updated_at' => '2018-01-01 10:03:58',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'external_system_id' => 1549,
                'payment_services_api_id' => 56,
                'name_ar' => 'Phone',
                'name_en' => 'Phone',
                'position' => 1,
                'visible' => 'yes',
                'required' => 'yes',
                'type' => 'N',
                'is_client_id' => 'yes',
                'default_value' => '',
                'min_length' => 5,
                'max_length' => 11,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:58',
                'updated_at' => '2018-01-01 10:03:58',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'external_system_id' => 1629,
                'payment_services_api_id' => 58,
                'name_ar' => 'serviceparamin1629',
                'name_en' => 'Phone',
                'position' => 1,
                'visible' => 'yes',
                'required' => 'yes',
                'type' => 'N',
                'is_client_id' => 'yes',
                'default_value' => '',
                'min_length' => 1,
                'max_length' => 100,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:58',
                'updated_at' => '2018-01-01 10:03:58',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'external_system_id' => 1309,
                'payment_services_api_id' => 59,
                'name_ar' => 'serviceparamin1309',
                'name_en' => 'Order ID',
                'position' => 1,
                'visible' => 'yes',
                'required' => 'yes',
                'type' => 'C',
                'is_client_id' => 'yes',
                'default_value' => '',
                'min_length' => 5,
                'max_length' => 15,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:58',
                'updated_at' => '2018-01-01 10:03:58',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'external_system_id' => 1310,
                'payment_services_api_id' => 60,
                'name_ar' => 'serviceparamin1310',
                'name_en' => 'Order ID',
                'position' => 1,
                'visible' => 'yes',
                'required' => 'yes',
                'type' => 'C',
                'is_client_id' => 'yes',
                'default_value' => '',
                'min_length' => 4,
                'max_length' => 15,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:58',
                'updated_at' => '2018-01-01 10:03:58',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'external_system_id' => 1255,
                'payment_services_api_id' => 61,
                'name_ar' => 'رقم حساب الطالب',
                'name_en' => 'Account Number',
                'position' => 1,
                'visible' => 'yes',
                'required' => 'yes',
                'type' => 'C',
                'is_client_id' => 'yes',
                'default_value' => '',
                'min_length' => 1,
                'max_length' => 20,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:59',
                'updated_at' => '2018-01-01 10:03:59',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'external_system_id' => 1256,
                'payment_services_api_id' => 61,
                'name_ar' => 'serviceparamin502',
                'name_en' => 'Biller ID',
                'position' => 2,
                'visible' => '',
                'required' => 'yes',
                'type' => 'C',
                'is_client_id' => '',
                'default_value' => '22661',
                'min_length' => 1,
                'max_length' => 5,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:59',
                'updated_at' => '2018-01-01 10:03:59',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'external_system_id' => 1257,
                'payment_services_api_id' => 61,
                'name_ar' => 'serviceparamin1257',
                'name_en' => 'Service Type',
                'position' => 5,
                'visible' => '',
                'required' => 'yes',
                'type' => 'C',
                'is_client_id' => '',
                'default_value' => 'CAU',
                'min_length' => 1,
                'max_length' => 3,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:59',
                'updated_at' => '2018-01-01 10:03:59',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'external_system_id' => 1249,
                'payment_services_api_id' => 62,
                'name_ar' => 'رقم حساب الطالب',
                'name_en' => 'Account Number',
                'position' => 1,
                'visible' => 'yes',
                'required' => 'yes',
                'type' => 'C',
                'is_client_id' => 'yes',
                'default_value' => '',
                'min_length' => 14,
                'max_length' => 20,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:59',
                'updated_at' => '2018-01-01 10:03:59',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'external_system_id' => 1250,
                'payment_services_api_id' => 62,
                'name_ar' => 'serviceparamin1250',
                'name_en' => 'Bill Number',
                'position' => 2,
                'visible' => '',
                'required' => '',
                'type' => 'C',
                'is_client_id' => '',
                'default_value' => '',
                'min_length' => 1,
                'max_length' => 20,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:59',
                'updated_at' => '2018-01-01 10:03:59',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'external_system_id' => 1251,
                'payment_services_api_id' => 62,
                'name_ar' => 'serviceparamin1251',
                'name_en' => 'ePay Bill Record ID',
                'position' => 3,
                'visible' => '',
                'required' => '',
                'type' => 'C',
                'is_client_id' => '',
                'default_value' => '',
                'min_length' => 1,
                'max_length' => 50,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:59',
                'updated_at' => '2018-01-01 10:03:59',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'external_system_id' => 1252,
                'payment_services_api_id' => 62,
                'name_ar' => 'serviceparamin1252',
                'name_en' => 'Fee Amount',
                'position' => 4,
                'visible' => '',
                'required' => '',
                'type' => 'C',
                'is_client_id' => '',
                'default_value' => '0',
                'min_length' => 1,
                'max_length' => 10,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:59',
                'updated_at' => '2018-01-01 10:03:59',
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'external_system_id' => 1253,
                'payment_services_api_id' => 62,
                'name_ar' => 'serviceparamin1253',
                'name_en' => 'Biller ID',
                'position' => 5,
                'visible' => '',
                'required' => '',
                'type' => 'L',
                'is_client_id' => '',
                'default_value' => '22661',
                'min_length' => 1,
                'max_length' => 5,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:59',
                'updated_at' => '2018-01-01 10:03:59',
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'external_system_id' => 1254,
                'payment_services_api_id' => 62,
                'name_ar' => 'serviceparamin1254',
                'name_en' => 'Service Type',
                'position' => 6,
                'visible' => '',
                'required' => '',
                'type' => 'C',
                'is_client_id' => '',
                'default_value' => 'CAU',
                'min_length' => 1,
                'max_length' => 3,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:59',
                'updated_at' => '2018-01-01 10:03:59',
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'external_system_id' => 620,
                'payment_services_api_id' => 63,
                'name_ar' => 'رقم حساب الطالب',
                'name_en' => 'Account Number',
                'position' => 1,
                'visible' => 'yes',
                'required' => 'yes',
                'type' => 'C',
                'is_client_id' => 'yes',
                'default_value' => '',
                'min_length' => 1,
                'max_length' => 20,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:59',
                'updated_at' => '2018-01-01 10:03:59',
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'external_system_id' => 621,
                'payment_services_api_id' => 63,
                'name_ar' => 'serviceparamin502',
                'name_en' => 'Biller ID',
                'position' => 2,
                'visible' => '',
                'required' => 'yes',
                'type' => 'C',
                'is_client_id' => '',
                'default_value' => '22661',
                'min_length' => 1,
                'max_length' => 5,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:59',
                'updated_at' => '2018-01-01 10:03:59',
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'external_system_id' => 622,
                'payment_services_api_id' => 63,
                'name_ar' => 'serviceparamin622',
                'name_en' => 'Service Type',
                'position' => 5,
                'visible' => '',
                'required' => 'yes',
                'type' => 'C',
                'is_client_id' => '',
                'default_value' => 'CAU',
                'min_length' => 1,
                'max_length' => 3,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:59',
                'updated_at' => '2018-01-01 10:03:59',
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'external_system_id' => 590,
                'payment_services_api_id' => 64,
                'name_ar' => 'رقم حساب الطالب',
                'name_en' => 'Account Number',
                'position' => 1,
                'visible' => 'yes',
                'required' => 'yes',
                'type' => 'C',
                'is_client_id' => 'yes',
                'default_value' => '',
                'min_length' => 14,
                'max_length' => 20,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:59',
                'updated_at' => '2018-01-01 10:03:59',
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'external_system_id' => 591,
                'payment_services_api_id' => 64,
                'name_ar' => 'serviceparamin591',
                'name_en' => 'Bill Number',
                'position' => 2,
                'visible' => '',
                'required' => '',
                'type' => 'C',
                'is_client_id' => '',
                'default_value' => '',
                'min_length' => 1,
                'max_length' => 20,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:59',
                'updated_at' => '2018-01-01 10:03:59',
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'external_system_id' => 592,
                'payment_services_api_id' => 64,
                'name_ar' => 'serviceparamin592',
                'name_en' => 'ePay Bill Record ID',
                'position' => 3,
                'visible' => '',
                'required' => '',
                'type' => 'C',
                'is_client_id' => '',
                'default_value' => '',
                'min_length' => 1,
                'max_length' => 50,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:59',
                'updated_at' => '2018-01-01 10:03:59',
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'external_system_id' => 593,
                'payment_services_api_id' => 64,
                'name_ar' => 'serviceparamin593',
                'name_en' => 'Fee Amount',
                'position' => 4,
                'visible' => '',
                'required' => '',
                'type' => 'C',
                'is_client_id' => '',
                'default_value' => '0',
                'min_length' => 1,
                'max_length' => 10,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:59',
                'updated_at' => '2018-01-01 10:03:59',
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'external_system_id' => 594,
                'payment_services_api_id' => 64,
                'name_ar' => 'serviceparamin594',
                'name_en' => 'Biller ID',
                'position' => 5,
                'visible' => '',
                'required' => '',
                'type' => 'L',
                'is_client_id' => '',
                'default_value' => '22661',
                'min_length' => 1,
                'max_length' => 5,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:59',
                'updated_at' => '2018-01-01 10:03:59',
                'deleted_at' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'external_system_id' => 595,
                'payment_services_api_id' => 64,
                'name_ar' => 'serviceparamin595',
                'name_en' => 'Service Type',
                'position' => 6,
                'visible' => '',
                'required' => '',
                'type' => 'C',
                'is_client_id' => '',
                'default_value' => 'CAU',
                'min_length' => 1,
                'max_length' => 3,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:59',
                'updated_at' => '2018-01-01 10:03:59',
                'deleted_at' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'external_system_id' => 241,
                'payment_services_api_id' => 65,
                'name_ar' => 'رقم العميل',
                'name_en' => 'Phone',
                'position' => 1,
                'visible' => 'yes',
                'required' => 'yes',
                'type' => 'N',
                'is_client_id' => 'yes',
                'default_value' => '01',
                'min_length' => 10,
                'max_length' => 11,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:59',
                'updated_at' => '2018-01-01 10:03:59',
                'deleted_at' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'external_system_id' => 224,
                'payment_services_api_id' => 66,
                'name_ar' => 'رقم العميل',
                'name_en' => 'Phone',
                'position' => 1,
                'visible' => 'yes',
                'required' => 'yes',
                'type' => 'N',
                'is_client_id' => 'yes',
                'default_value' => '01',
                'min_length' => 10,
                'max_length' => 11,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:59',
                'updated_at' => '2018-01-01 10:03:59',
                'deleted_at' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'external_system_id' => 1294,
                'payment_services_api_id' => 67,
                'name_ar' => 'serviceparamin1294',
                'name_en' => 'Customer Number',
                'position' => 1,
                'visible' => 'yes',
                'required' => 'yes',
                'type' => 'N',
                'is_client_id' => 'yes',
                'default_value' => '',
                'min_length' => 7,
                'max_length' => 11,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:59',
                'updated_at' => '2018-01-01 10:03:59',
                'deleted_at' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'external_system_id' => 1295,
                'payment_services_api_id' => 68,
                'name_ar' => 'serviceparamin1295',
                'name_en' => 'Customer Number',
                'position' => 1,
                'visible' => 'yes',
                'required' => 'yes',
                'type' => 'N',
                'is_client_id' => 'yes',
                'default_value' => '',
                'min_length' => 7,
                'max_length' => 11,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:59',
                'updated_at' => '2018-01-01 10:03:59',
                'deleted_at' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'external_system_id' => 1269,
                'payment_services_api_id' => 69,
                'name_ar' => 'serviceparamin1269',
                'name_en' => 'Phone',
                'position' => 1,
                'visible' => 'yes',
                'required' => 'yes',
                'type' => 'N',
                'is_client_id' => 'yes',
                'default_value' => '',
                'min_length' => 11,
                'max_length' => 11,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:04:00',
                'updated_at' => '2018-01-01 10:04:00',
                'deleted_at' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'external_system_id' => 281,
                'payment_services_api_id' => 70,
                'name_ar' => 'serviceparamin281',
                'name_en' => 'phone',
                'position' => 1,
                'visible' => 'yes',
                'required' => 'yes',
                'type' => 'N',
                'is_client_id' => 'yes',
                'default_value' => '010',
                'min_length' => 10,
                'max_length' => 11,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:04:00',
                'updated_at' => '2018-01-01 10:04:00',
                'deleted_at' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'external_system_id' => 62,
                'payment_services_api_id' => 71,
                'name_ar' => 'رقم العميل',
                'name_en' => 'Phone',
                'position' => 1,
                'visible' => 'yes',
                'required' => 'yes',
                'type' => 'N',
                'is_client_id' => 'yes',
                'default_value' => '01',
                'min_length' => 9,
                'max_length' => 11,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:04:00',
                'updated_at' => '2018-01-01 10:04:00',
                'deleted_at' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'external_system_id' => 61,
                'payment_services_api_id' => 72,
                'name_ar' => 'رقم العميل',
                'name_en' => 'Phone',
                'position' => 1,
                'visible' => 'yes',
                'required' => 'yes',
                'type' => 'N',
                'is_client_id' => 'yes',
                'default_value' => '011',
                'min_length' => 9,
                'max_length' => 11,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:04:00',
                'updated_at' => '2018-01-01 10:04:00',
                'deleted_at' => NULL,
            ),
            70 => 
            array (
                'id' => 71,
                'external_system_id' => 261,
                'payment_services_api_id' => 73,
                'name_ar' => 'serviceparamin261',
                'name_en' => 'phone',
                'position' => 1,
                'visible' => 'yes',
                'required' => 'yes',
                'type' => 'N',
                'is_client_id' => 'yes',
                'default_value' => '01',
                'min_length' => 10,
                'max_length' => 11,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:04:00',
                'updated_at' => '2018-01-01 10:04:00',
                'deleted_at' => NULL,
            ),
            71 => 
            array (
                'id' => 72,
                'external_system_id' => 63,
                'payment_services_api_id' => 74,
                'name_ar' => 'رقم العميل',
                'name_en' => 'Phone',
                'position' => 1,
                'visible' => 'yes',
                'required' => 'yes',
                'type' => 'N',
                'is_client_id' => 'yes',
                'default_value' => '012',
                'min_length' => 10,
                'max_length' => 11,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:04:00',
                'updated_at' => '2018-01-01 10:04:00',
                'deleted_at' => NULL,
            ),
            72 => 
            array (
                'id' => 73,
                'external_system_id' => 888,
                'payment_services_api_id' => 75,
            'name_ar' => 'كود الدفع  (جنوب القاهرة =99007 – الإسكندرية = 99021 – البحيرة =99022 – شمال القاهرة = 99023 – شمال القاهرة = 99025 )',
            'name_en' => 'كود الدفع  (جنوب القاهرة =99007 – الإسكندرية = 99021 – البحيرة =99022 – شمال القاهرة = 99023 – شمال القاهرة = 99025 )',
                'position' => 2,
                'visible' => '',
                'required' => 'yes',
                'type' => 'N',
                'is_client_id' => '',
                'default_value' => '99025',
                'min_length' => 1,
                'max_length' => 5,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:04:00',
                'updated_at' => '2018-01-01 10:04:00',
                'deleted_at' => NULL,
            ),
            73 => 
            array (
                'id' => 74,
                'external_system_id' => 889,
                'payment_services_api_id' => 75,
                'name_ar' => 'serviceparamin889',
                'name_en' => 'Service Type',
                'position' => 5,
                'visible' => '',
                'required' => 'yes',
                'type' => 'C',
                'is_client_id' => '',
                'default_value' => 'ECP',
                'min_length' => 1,
                'max_length' => 3,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:04:00',
                'updated_at' => '2018-01-01 10:04:00',
                'deleted_at' => NULL,
            ),
            74 => 
            array (
                'id' => 75,
                'external_system_id' => 891,
                'payment_services_api_id' => 75,
                'name_ar' => 'serviceparamin891',
                'name_en' => 'Account Number',
                'position' => 1,
                'visible' => 'yes',
                'required' => 'yes',
                'type' => 'N',
                'is_client_id' => 'yes',
                'default_value' => '',
                'min_length' => 1,
                'max_length' => 20,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:04:00',
                'updated_at' => '2018-01-01 10:04:00',
                'deleted_at' => NULL,
            ),
            75 => 
            array (
                'id' => 76,
                'external_system_id' => 875,
                'payment_services_api_id' => 76,
                'name_ar' => 'رقم حساب العميل',
                'name_en' => 'Account Number',
                'position' => 1,
                'visible' => 'yes',
                'required' => 'yes',
                'type' => 'N',
                'is_client_id' => 'yes',
                'default_value' => '',
                'min_length' => 1,
                'max_length' => 20,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:04:00',
                'updated_at' => '2018-01-01 10:04:00',
                'deleted_at' => NULL,
            ),
            76 => 
            array (
                'id' => 77,
                'external_system_id' => 876,
                'payment_services_api_id' => 76,
                'name_ar' => 'serviceparamin876',
                'name_en' => 'Bill Number',
                'position' => 2,
                'visible' => '',
                'required' => '',
                'type' => 'C',
                'is_client_id' => '',
                'default_value' => '',
                'min_length' => 1,
                'max_length' => 20,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:04:00',
                'updated_at' => '2018-01-01 10:04:00',
                'deleted_at' => NULL,
            ),
            77 => 
            array (
                'id' => 78,
                'external_system_id' => 877,
                'payment_services_api_id' => 76,
                'name_ar' => 'serviceparamin877',
                'name_en' => 'ePay Bill Record ID',
                'position' => 3,
                'visible' => '',
                'required' => '',
                'type' => 'C',
                'is_client_id' => '',
                'default_value' => '',
                'min_length' => 1,
                'max_length' => 50,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:04:00',
                'updated_at' => '2018-01-01 10:04:00',
                'deleted_at' => NULL,
            ),
            78 => 
            array (
                'id' => 79,
                'external_system_id' => 878,
                'payment_services_api_id' => 76,
                'name_ar' => 'serviceparamin878',
                'name_en' => 'Fee Amount',
                'position' => 4,
                'visible' => '',
                'required' => '',
                'type' => 'C',
                'is_client_id' => '',
                'default_value' => '0',
                'min_length' => 1,
                'max_length' => 10,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:04:00',
                'updated_at' => '2018-01-01 10:04:00',
                'deleted_at' => NULL,
            ),
            79 => 
            array (
                'id' => 80,
                'external_system_id' => 879,
                'payment_services_api_id' => 76,
            'name_ar' => 'كود الدفع  (جنوب القاهرة =99007 – الإسكندرية = 99021 – البحيرة =99022 – شمال القاهرة = 99023 – شمال القاهرة = 99025 )',
            'name_en' => 'Biller ID (Sout Cairo=99007 , Alex= 99021 ,Behara= 99022, North Cairo= 99023,North Cairo= 99024,North Cairo= 99025)',
                'position' => 5,
                'visible' => '',
                'required' => 'yes',
                'type' => 'N',
                'is_client_id' => '',
                'default_value' => '99025',
                'min_length' => 1,
                'max_length' => 5,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:04:00',
                'updated_at' => '2018-01-01 10:04:00',
                'deleted_at' => NULL,
            ),
            80 => 
            array (
                'id' => 81,
                'external_system_id' => 880,
                'payment_services_api_id' => 76,
                'name_ar' => 'serviceparamin880',
                'name_en' => 'Service Type',
                'position' => 6,
                'visible' => '',
                'required' => '',
                'type' => 'C',
                'is_client_id' => '',
                'default_value' => 'ECP',
                'min_length' => 1,
                'max_length' => 3,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:04:00',
                'updated_at' => '2018-01-01 10:04:00',
                'deleted_at' => NULL,
            ),
            81 => 
            array (
                'id' => 82,
                'external_system_id' => 501,
                'payment_services_api_id' => 77,
                'name_ar' => 'رقم حساب العميل',
                'name_en' => 'Account Number',
                'position' => 1,
                'visible' => 'yes',
                'required' => 'yes',
                'type' => 'N',
                'is_client_id' => 'yes',
                'default_value' => '',
                'min_length' => 1,
                'max_length' => 20,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:04:00',
                'updated_at' => '2018-01-01 10:04:00',
                'deleted_at' => NULL,
            ),
            82 => 
            array (
                'id' => 83,
                'external_system_id' => 502,
                'payment_services_api_id' => 77,
                'name_ar' => 'serviceparamin502',
                'name_en' => 'Biller ID',
                'position' => 2,
                'visible' => '',
                'required' => 'yes',
                'type' => 'C',
                'is_client_id' => '',
                'default_value' => '99007',
                'min_length' => 1,
                'max_length' => 5,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:04:00',
                'updated_at' => '2018-01-01 10:04:00',
                'deleted_at' => NULL,
            ),
            83 => 
            array (
                'id' => 84,
                'external_system_id' => 506,
                'payment_services_api_id' => 77,
                'name_ar' => 'serviceparamin506',
                'name_en' => 'Service Type',
                'position' => 5,
                'visible' => '',
                'required' => 'yes',
                'type' => 'C',
                'is_client_id' => '',
                'default_value' => 'ECP',
                'min_length' => 1,
                'max_length' => 3,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:04:00',
                'updated_at' => '2018-01-01 10:04:00',
                'deleted_at' => NULL,
            ),
            84 => 
            array (
                'id' => 85,
                'external_system_id' => 869,
                'payment_services_api_id' => 78,
                'name_ar' => 'رقم حساب العميل',
                'name_en' => 'Account Number',
                'position' => 1,
                'visible' => 'yes',
                'required' => 'yes',
                'type' => 'N',
                'is_client_id' => 'yes',
                'default_value' => '',
                'min_length' => 1,
                'max_length' => 20,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:04:00',
                'updated_at' => '2018-01-01 10:04:00',
                'deleted_at' => NULL,
            ),
            85 => 
            array (
                'id' => 86,
                'external_system_id' => 870,
                'payment_services_api_id' => 78,
                'name_ar' => 'serviceparamin870',
                'name_en' => 'Bill Number',
                'position' => 2,
                'visible' => '',
                'required' => '',
                'type' => 'C',
                'is_client_id' => '',
                'default_value' => '',
                'min_length' => 1,
                'max_length' => 20,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:04:00',
                'updated_at' => '2018-01-01 10:04:00',
                'deleted_at' => NULL,
            ),
            86 => 
            array (
                'id' => 87,
                'external_system_id' => 871,
                'payment_services_api_id' => 78,
                'name_ar' => 'serviceparamin871',
                'name_en' => 'ePay Bill Record ID',
                'position' => 3,
                'visible' => '',
                'required' => '',
                'type' => 'C',
                'is_client_id' => '',
                'default_value' => '',
                'min_length' => 1,
                'max_length' => 50,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:04:00',
                'updated_at' => '2018-01-01 10:04:00',
                'deleted_at' => NULL,
            ),
            87 => 
            array (
                'id' => 88,
                'external_system_id' => 872,
                'payment_services_api_id' => 78,
                'name_ar' => 'serviceparamin872',
                'name_en' => 'Fee Amount',
                'position' => 4,
                'visible' => '',
                'required' => '',
                'type' => 'C',
                'is_client_id' => '',
                'default_value' => '0',
                'min_length' => 1,
                'max_length' => 10,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:04:01',
                'updated_at' => '2018-01-01 10:04:01',
                'deleted_at' => NULL,
            ),
            88 => 
            array (
                'id' => 89,
                'external_system_id' => 873,
                'payment_services_api_id' => 78,
                'name_ar' => 'serviceparamin873',
                'name_en' => 'Biller ID',
                'position' => 5,
                'visible' => '',
                'required' => 'yes',
                'type' => 'C',
                'is_client_id' => '',
                'default_value' => '66601',
                'min_length' => 1,
                'max_length' => 5,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:04:01',
                'updated_at' => '2018-01-01 10:04:01',
                'deleted_at' => NULL,
            ),
            89 => 
            array (
                'id' => 90,
                'external_system_id' => 874,
                'payment_services_api_id' => 78,
                'name_ar' => 'serviceparamin874',
                'name_en' => 'Service Type',
                'position' => 6,
                'visible' => '',
                'required' => '',
                'type' => 'C',
                'is_client_id' => '',
                'default_value' => 'ECP',
                'min_length' => 1,
                'max_length' => 3,
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:04:01',
                'updated_at' => '2018-01-01 10:04:01',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}