<?php

use Illuminate\Database\Seeder;

class PaymentServicesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('payment_services')->delete();
        
        \DB::table('payment_services')->insert(array (
            0 => 
            array (
                'id' => 1,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 4908,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'فكة - 0.5',
                'name_en' => 'Fakka - 0.5',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:54',
                'updated_at' => '2018-01-01 10:03:54',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 4908,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'فكة - 1.25',
                'name_en' => 'Fakka - 1.25',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:54',
                'updated_at' => '2018-01-01 10:03:54',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 4908,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'فكة - 2.5',
                'name_en' => 'Fakka - 2.5',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:54',
                'updated_at' => '2018-01-01 10:03:54',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 4908,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'فكة - 3',
                'name_en' => 'Fakka - 3',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:54',
                'updated_at' => '2018-01-01 10:03:54',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 4908,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'فكة - 3.5',
                'name_en' => 'Fakka - 3.5',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:54',
                'updated_at' => '2018-01-01 10:03:54',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 4908,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'فكة - 4',
                'name_en' => 'Fakka - 4',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:54',
                'updated_at' => '2018-01-01 10:03:54',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 4908,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'مارد النت',
                'name_en' => 'Mared El Net',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:54',
                'updated_at' => '2018-01-01 10:03:54',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 4908,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'كارت 10',
                'name_en' => 'card 10',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:54',
                'updated_at' => '2018-01-01 10:03:54',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 4908,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'كوبون فودافون - 10',
                'name_en' => 'Vodafone Coupon-10',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:54',
                'updated_at' => '2018-01-01 10:03:54',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 4908,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'كوبون فودافون-15',
                'name_en' => 'Vodafone Coupon-15',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:54',
                'updated_at' => '2018-01-01 10:03:54',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 4908,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'كوبون فودافون-25',
                'name_en' => 'Vodafone Coupon-25',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:54',
                'updated_at' => '2018-01-01 10:03:54',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 4908,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'كوبون فودافون-50',
                'name_en' => 'Vodafone Coupon-50',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:54',
                'updated_at' => '2018-01-01 10:03:54',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 4908,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'كوبون فودافون-100',
                'name_en' => 'Vodafone Coupon-100',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:54',
                'updated_at' => '2018-01-01 10:03:54',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 4908,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'كوبون فودافون-200',
                'name_en' => 'Vodafone Coupon-200',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:54',
                'updated_at' => '2018-01-01 10:03:54',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 11521,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'شحن هوا',
                'name_en' => 'Topup',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'yes',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:54',
                'updated_at' => '2018-01-01 10:03:54',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 11523,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'شحن هوا',
                'name_en' => 'TopUp',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'yes',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:55',
                'updated_at' => '2018-01-01 10:03:55',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 11522,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'شحن هوا',
                'name_en' => 'Etisalat Recharge',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'yes',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:55',
                'updated_at' => '2018-01-01 10:03:55',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 1912,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => '10سلك-6ج',
                'name_en' => '10 Silk - 6LE',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:55',
                'updated_at' => '2018-01-01 10:03:55',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 1912,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => '50سلك-30ج',
                'name_en' => '50 Silk - 30LE',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:55',
                'updated_at' => '2018-01-01 10:03:55',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 1912,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => '100سلك-60ج',
                'name_en' => '100 Silk - 60LE',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:55',
                'updated_at' => '2018-01-01 10:03:55',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 1912,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => '300سلك-180ج',
                'name_en' => '300 Silk - 180LE',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:55',
                'updated_at' => '2018-01-01 10:03:55',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 1912,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => '500سلك-300ج',
                'name_en' => '500 Silk - 300LE',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:55',
                'updated_at' => '2018-01-01 10:03:55',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 1912,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => '1000سلك-600ج',
                'name_en' => '1000 Silk - 600LE',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:55',
                'updated_at' => '2018-01-01 10:03:55',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 1917,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'استعلام حساب',
                'name_en' => 'Get Account Info',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:55',
                'updated_at' => '2018-01-01 10:03:55',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 1917,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'شحن حساب',
                'name_en' => 'Topup Account',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'yes',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:55',
                'updated_at' => '2018-01-01 10:03:55',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 1911,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'تحدي 150ن-15ج',
                'name_en' => 'Tahadi 150P - 15LE',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:55',
                'updated_at' => '2018-01-01 10:03:55',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 1911,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'تحدي 475ن-45ج',
                'name_en' => 'Tahadi 475P - 45LE',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:55',
                'updated_at' => '2018-01-01 10:03:55',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 1911,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'تحدي 850ن-75ج',
                'name_en' => 'Tahadi 850P - 75LE',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:55',
                'updated_at' => '2018-01-01 10:03:55',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 1911,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => '1,000 JP - 6 LE',
                'name_en' => 'Tahadi 1800P - 150LE',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:56',
                'updated_at' => '2018-01-01 10:03:56',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 10261,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'صندوق تحيا مصر',
                'name_en' => 'Tahya Misr Funding',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'yes',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:56',
                'updated_at' => '2018-01-01 10:03:56',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 8566,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'دفع مصاريف',
                'name_en' => 'Tuition Fees',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:56',
                'updated_at' => '2018-01-01 10:03:56',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 8566,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'دفع مصاريف',
                'name_en' => 'Tuition Fees',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:56',
                'updated_at' => '2018-01-01 10:03:56',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 8565,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'دفع مصاريف',
                'name_en' => 'Tuition Fees',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:56',
                'updated_at' => '2018-01-01 10:03:56',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 8564,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'دفع مصاريف',
                'name_en' => 'Tuition Fees',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:56',
                'updated_at' => '2018-01-01 10:03:56',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 7702,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'Bee Card',
                'name_en' => 'Bee Card',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:57',
                'updated_at' => '2018-01-01 10:03:57',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 7512,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'كارت 10$- 80ج.م',
                'name_en' => 'iTunes $10 Card - 80 LE',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:57',
                'updated_at' => '2018-01-01 10:03:57',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 7512,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'كارت 15$- 115ج.م',
                'name_en' => 'iTunes $15 Card -115 LE',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:57',
                'updated_at' => '2018-01-01 10:03:57',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 7512,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'كارت 25$- 180ج.م',
                'name_en' => 'iTunes $25 Card -180 LE',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:57',
                'updated_at' => '2018-01-01 10:03:57',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 7512,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'كارت 50$- 350ج.م',
                'name_en' => 'iTunes $50 Card - 350 LE',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:57',
                'updated_at' => '2018-01-01 10:03:57',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 7510,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'كارت زينجا $2 - 13 ج.م',
                'name_en' => 'Zynga $2 Card - 13 LE',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:57',
                'updated_at' => '2018-01-01 10:03:57',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 7510,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'كارت زينجا $5 - 32 ج.م',
                'name_en' => 'Zynga $5 Card - 32 LE',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:57',
                'updated_at' => '2018-01-01 10:03:57',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 7510,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'كارت زينجا $10 - 65 ج.م',
                'name_en' => 'Zynga $10 Card - 65 LE',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:57',
                'updated_at' => '2018-01-01 10:03:57',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 7510,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'كارت زينجا $20 - 130 ج.م',
                'name_en' => 'Zynga $20 Card - 130 LE',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:57',
                'updated_at' => '2018-01-01 10:03:57',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 7509,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'كارت 3 شهور - 150ج.م',
                'name_en' => 'X-Box 3 Months - 40 $',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:57',
                'updated_at' => '2018-01-01 10:03:57',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 7509,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'كارت 12 شهر - 340ج.م',
                'name_en' => 'X-Box 12 Months - 20 $',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:57',
                'updated_at' => '2018-01-01 10:03:57',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 7509,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'كارت 1,600 - 150ج.م',
                'name_en' => 'X-Box 16,00 Point - US - 40 $',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:57',
                'updated_at' => '2018-01-01 10:03:57',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 7509,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'كارت 4,000 - 340ج.م',
                'name_en' => 'X-Box 4,000 Point - US - 80 $',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:57',
                'updated_at' => '2018-01-01 10:03:57',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 7508,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'كارت $10 -  90 ج.م',
                'name_en' => 'Playstation 3 $10 - 90 LE',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:57',
                'updated_at' => '2018-01-01 10:03:57',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 7508,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'كارت $20 -  160 ج.م',
                'name_en' => 'Playstation 3 $20 - 160 LE',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:57',
                'updated_at' => '2018-01-01 10:03:57',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 7508,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'كارت $50 -  375 ج.م',
                'name_en' => 'Playstation 3 $50 - 375 LE',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:58',
                'updated_at' => '2018-01-01 10:03:58',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 10941,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'service10942',
                'name_en' => 'BFCE',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:58',
                'updated_at' => '2018-01-01 10:03:58',
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 4974,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'كروت شحن اورنج',
                'name_en' => 'Orange EV',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:58',
                'updated_at' => '2018-01-01 10:03:58',
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 4838,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'service10161',
                'name_en' => 'TAL2A-5GB-25LE',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:58',
                'updated_at' => '2018-01-01 10:03:58',
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 5,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => '10;15;25;50;100',
                'name_en' => 'E-Vouchers',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:58',
                'updated_at' => '2018-01-01 10:03:58',
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 8441,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'دفع فواتير الكهرباء',
                'name_en' => 'Pay All Bills',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:58',
                'updated_at' => '2018-01-01 10:03:58',
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 12243,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'TE GSM Topup',
                'name_en' => 'TE GSM Topup',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:58',
                'updated_at' => '2018-01-01 10:03:58',
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 12243,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'TE GSM Evoucher 100',
                'name_en' => 'TE GSM Evoucher 100',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:58',
                'updated_at' => '2018-01-01 10:03:58',
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 4976,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'service11361',
                'name_en' => 'Mubasher Mobile',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:58',
                'updated_at' => '2018-01-01 10:03:58',
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 10321,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'service10322',
                'name_en' => 'Inquiry',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:58',
                'updated_at' => '2018-01-01 10:03:58',
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 8563,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'Science - Tuition Inquiry',
                'name_en' => 'Science - Tuition Inquiry',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:58',
                'updated_at' => '2018-01-01 10:03:58',
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 8563,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'إستعلام',
                'name_en' => 'Commerce - Tuition Inquiry',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:59',
                'updated_at' => '2018-01-01 10:03:59',
                'deleted_at' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 4839,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'استعلام فاتورة',
                'name_en' => 'Bill Inquiry',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:59',
                'updated_at' => '2018-01-01 10:03:59',
                'deleted_at' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 4838,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'استعلام فاتورة',
                'name_en' => 'Bill inquiry',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:59',
                'updated_at' => '2018-01-01 10:03:59',
                'deleted_at' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 581,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'استعلام فاتورة',
                'name_en' => 'Bill inquiry',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:03:59',
                'updated_at' => '2018-01-01 10:03:59',
                'deleted_at' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 3,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'استعلام فاتورة',
                'name_en' => 'Bill Inquiry',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:04:00',
                'updated_at' => '2018-01-01 10:04:00',
                'deleted_at' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 5,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'استعلام فاتورة',
                'name_en' => 'Bill inquiry',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:04:00',
                'updated_at' => '2018-01-01 10:04:00',
                'deleted_at' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 8441,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'Inquire All Bills',
                'name_en' => 'Inquire Oldest Bill',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:04:00',
                'updated_at' => '2018-01-01 10:04:00',
                'deleted_at' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'payment_sdk_id' => 1,
                'payment_service_provider_id' => 8441,
                'payment_output_id' => 1,
                'commission_list_id' => 1,
                'name_ar' => 'استعلام',
                'name_en' => 'mc electricity inquiry',
                'description_ar' => NULL,
                'description_en' => NULL,
                'request_amount_input' => 'no',
                'status' => 'active',
                'icon' => 'icons/service2.png',
                'staff_id' => 1,
                'created_at' => '2018-01-01 10:04:00',
                'updated_at' => '2018-01-01 10:04:00',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}